print("M")
print("A")
print("M")
print("A")
print("B")
print("O")
print("Y")
print("Mama's boy")
print("Mama's boy")
print("Mama's boy")
print("Mama's boy")
print("M")
print("A")
print("M")
print("A")
print("B")
print("O")
print("Y")
print("Mama's boy")
print("Mama's boy")
print("M")
print("A")
print("M")
print("A")
print("B")
print("O")
print("Y")
print("Mama's boy")
print("Mama's boy")